export const butacas = [
    {
        id: "1",
        fila: "A",
        numero: "1",
        description: "butaca A1",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "2",
        fila: "A",
        numero: "2",
        description: "butaca A2",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "3",
        fila: "A",
        numero: "3",
        description: "butaca A3",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "4",
        fila: "A",
        numero: "4",
        description: "butaca A4",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "5",
        fila: "A",
        numero: "5",
        description: "butaca A5",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "6",
        fila: "A",
        numero: "6",
        description: "butaca A6",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "7",
        fila: "A",
        numero: "7",
        description: "butaca A7",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "8",
        fila: "A",
        numero: "8",
        description: "butaca A8",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "9",
        fila: "A",
        numero: "9",
        description: "butaca A9",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "10",
        fila: "A",
        numero: "10",
        description: "butaca A10",
        category: "primera fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "1",
        fila: "B",
        numero: "1",
        description: "butaca B1",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "2",
        fila: "B",
        numero: "2",
        description: "butaca B2",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "3",
        fila: "B",
        numero: "3",
        description: "butaca B3",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "4",
        fila: "B",
        numero: "4",
        description: "butaca B4",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "5",
        fila: "B",
        numero: "5",
        description: "butaca B5",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "6",
        fila: "B",
        numero: "6",
        description: "butaca B6",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "7",
        fila: "B",
        numero: "7",
        description: "butaca B7",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "8",
        fila: "B",
        numero: "8",
        description: "butaca B8",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "9",
        fila: "B",
        numero: "9",
        description: "butaca B9",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "10",
        fila: "B",
        numero: "10",
        description: "butaca B10",
        category: "segunda fila",
        stock: 1,
        price: "$500",
    },
    {
        id: "1",
        fila: "C",
        numero: "1",
        description: "butaca C1",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "2",
        fila: "C",
        numero: "2",
        description: "butaca C2",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "3",
        fila: "C",
        numero: "3",
        description: "butaca C3",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "4",
        fila: "C",
        numero: "4",
        description: "butaca C4",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "5",
        fila: "C",
        numero: "5",
        description: "butaca C5",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "6",
        fila: "C",
        numero: "6",
        description: "butaca C6",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "7",
        fila: "C",
        numero: "7",
        description: "butaca C7",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "8",
        fila: "C",
        numero: "8",
        description: "butaca C8",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "9",
        fila: "C",
        numero: "9",
        description: "butaca C9",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "10",
        fila: "C",
        numero: "10",
        description: "butaca C10",
        category: "tercera fila",
        stock: 1,
        price: "$400",
    },
    {
        id: "1",
        fila: "D",
        numero: "1",
        description: "butaca D1",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "2",
        fila: "D",
        numero: "2",
        description: "butaca D2",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "3",
        fila: "D",
        numero: "3",
        description: "butaca D3",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "4",
        fila: "D",
        numero: "4",
        description: "butaca D4",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "5",
        fila: "D",
        numero: "5",
        description: "butaca D5",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "6",
        fila: "D",
        numero: "6",
        description: "butaca D6",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "7",
        fila: "D",
        numero: "7",
        description: "butaca D7",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "8",
        fila: "D",
        numero: "8",
        description: "butaca D8",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "9",
        fila: "D",
        numero: "9",
        description: "butaca D9",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    },
    {
        id: "10",
        fila: "D",
        numero: "10",
        description: "butaca D10",
        category: "cuarta fila",
        stock: 1,
        price: "$300",
    }
];